root = /
db = /var/lib/flash/flash.db
cache = /var/cache/flash
build_dir = /var/cache/flash/build
recipes = /var/lib/flash/recipes
sandbox = true
jobs = 4
source_threshold = 104857600
binary_threshold = 471859200
